### ISSUE TITLE
Implement strict typing

### ISSUE THREAD

**Issue by jacobdekeizer** [mvdnbrk/dhlparcel-php-api#18]
Hi @mvdnbrk , can I implement strict return types and strict parameters?

**Comment by mvdnbrk** [comment]
I am not against it, however to keep the code consistent we should update a lot of code.
I am not a huge fan of mixing strict types in some places while other parts are not strict typed.

**Comment by jacobdekeizer** [comment]
@mvdnbrk Strict typing enforces developers to write better code. I think it's a good step to make code strict where possible and skip methods like setPiecesAttribute which accept two types. But it's up to you to decide :), the package is not on version 1.0 yet so we can make some breaking changes.

**Comment by mvdnbrk** [comment]
Like I said I am not against it 😄 

Please feel free to open a new pull request.
