### ISSUE TITLE
Passing shipment to labels gets only first label

### ISSUE THREAD

**Issue by Thorry84** [mvdnbrk/dhlparcel-php-api#39]
**Describe the bug**
The documentation says:

> Or you may pass the Shipment instance directly to this method:

`$dhlparcel->labels->get($shipment);`

But when the shipment contains multiple pieces, only the first piece is used.

**To Reproduce**

Create a shipment with multiple labels. Get the labels using:

`$dhlparcel->labels->get($shipment);`

**Expected behavior**
I would expect a PDF file containing all labels for the shipment.

**Please complete the following information:**
 - Version of this package: 0.8.0
 - PHP Version: 7.1.15

**Comment by Thorry84** [comment]
This has been discussed multiple times before, having seperate code paths for a single piece shipment and multiple pieces leads to duplicate code, confusion and incompatibility issues. A single code path should exist for all shipment, regardless of the number of pieces.

I suggest removing the label_id and barcode properties from shipment and either combine the labels for a shipment when a shipment is given, or not accept a shipment as a parameter for getting labels.

A shipment does not have a label, a shipment has pieces and a piece has a label. The code should reflect this simple reality.

**Comment by mvdnbrk** [comment]
If you have multiple pieces you should make multiple requests to the `labels` endpoint to retrieve the labels one by one. 

Feel free to submit a PR to improve things.

**Comment by Thorry84** [comment]
I would suggest not closing the issue before the issue has been resolved. If you don't want to fix it, just leave it open so people can at least see the documentation and/or code has issues.

**Comment by mvdnbrk** [comment]
I have updated the documentation to point this out.

It is not considered as a bug.
