### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by gizburdt** [mvdnbrk/dhlparcel-php-api#57]
Hi, would be awesome if the package could support PHP 8 :)

If it helps, I can make a PR to change PHP to >=7.2

**Comment by mvdnbrk** [comment]
Sure will update the workflows to test against PHP 8 :smile:

**Comment by gizburdt** [comment]
Awesome!

**Comment by mvdnbrk** [comment]
Released in v1.4.0
