### ISSUE TITLE
Is there support for "Evening Delivery", "Extra Insured"?

### ISSUE THREAD

**Issue by noromamai** [mvdnbrk/dhlparcel-php-api#61]
Just started using your package to implement DHL label printing in a project (labels are printed after packing, so number of labels and package type will be decided at the end). Shipping options are retrieved from a Magento2 site. The DHLParcel extension for Magento2 has options to choose for a evening delivery or insure the package. Package insurance is not selectable for the customer, but an evening delivery is. The shipment type will be "DOOR,EVE" instead of "DOOR". I could not see any support for this in the code I think. Could this be implemented?

It would be nice to have an option like $parcel->isEveningDelivery() and $parcel->isExtraEnsured()

**Comment by mvdnbrk** [comment]
This is currently not supported with this package. Feel free to open a PR.

**Comment by bastiaansenglenn** [comment]
I just made a PR for the insured shipping option @noromamai, hopefully this helps you as well!

https://github.com/mvdnbrk/dhlparcel-php-api/pull/63
