### ISSUE TITLE
Extend the API with more detailed track&trace info

### ISSUE THREAD

**Issue by rickyheijnen** [mvdnbrk/dhlparcel-php-api#62]
**Is your feature request related to a problem? Please describe.**
There is a lot of track and trace information available in the /track-trace API response, but your TrackTrace Resource is only limited to isDelivered
See: https://api-gw.dhlparcel.nl/docs/#/track-trace/getTrackAndTrace

**Describe the solution you'd like**
It would be nice if the TrackTrace Resource could be extended with all the information that is available in the track-trace API response like the width, height, length of the parcel and all the tracking events

**Comment by mvdnbrk** [comment]
Feel free to submit a PR which adds the additional information you need in the TrackTrace resource.
