### ISSUE TITLE
Downloading a label makes the app crash

### ISSUE THREAD

**Issue by rickyheijnen** [mvdnbrk/dhlparcel-php-api#64]
This line generates a fatal error:
`$dhlparcel->labels->get($label_id);`

Fatal error: in /var/www/html/vendor/mvdnbrk/dhlparcel-php-api/src/Endpoints/BaseEndpoint.php on line 68

**Expected behavior**
The shipment label should be returned in PDF

**Please complete the following information:**
 - Version of this package: 1.4.0
 - PHP Version: 7.3.27

**Comment by bastiaansenglenn** [comment]
@rickyheijnen  I encountered the same problem and solved it like this;

```
$this->client = new \Mvdnbrk\DhlParcel\Client();
$token           = $this->client->authentication->getAccessToken();
$labelResult  = $this->client->performHttpCall(
                'GET',
                'labels/' . $labelId,
                null,
                [
                    'Accept' => 'application/pdf',
                    'Authorization' => 'Bearer ' . $token->token
                ]
            );
```

**Comment by rickyheijnen** [comment]
Thank you! That is a solid solution and I used kind of the same solution to have a quick workaround. But its better solve this in this PHP API so a solution is available for everybody without having to change their own code.
