### ISSUE TITLE
Improve error handling and reporting

### ISSUE THREAD

**Issue by olia-bn** [mvdnbrk/dhlparcel-php-api#66]
**Is your feature request related to a problem? Please describe.**
When handling an API call (`BaseEndpoint->performApiCall`), bundle first checks for JSON error and throws generic "Unable to decode DHL Parcel response", with no status code. Status of the response is only checked afterwards.

This means that if for example, an Unauthorized exception is thrown, instead of descriptive Exception with message and status code, we only get the generic message (because response body is empty and thus json decode results in an error).

**Describe the solution you'd like**
Checking status code of the response and throwing a descriptive exception should happen before checking for json decode error.

**Describe alternatives you've considered**

**Comment by mvdnbrk** [comment]
Feel free to open a PR for improvements on this.
