### ISSUE TITLE
How do I properly add reference?

### ISSUE THREAD

**Issue by olia-bn** [mvdnbrk/dhlparcel-php-api#67]
**Describe the bug**
I have a problem setting a reference on the package.

Code example from `README.md` indicates to use `reference`:
```
$parcel = new \Mvdnbrk\DhlParcel\Resources\Parcel([
    'reference' => 'your own reference for the parcel (optional)',
    ...
```

but code at `Mvdnbrk\DhlParcel\Resources\Parcel` seems to be using `reference_identifier` (lines 32 and 147 for getter and setter and line 161 when collecting).

I tried using both `reference` and `reference_identifier` in attribute array as well as the setter, but on the label the reference field shows empty. Customer reports he does not see the reference in his dashboard either (though I do not have access to the dashboard).

What is the proper way to set a reference and to make it display on the label?

 - Version of this package: 1.4.1
 - PHP Version: 7.2

**Comment by mvdnbrk** [comment]
See this section to add a description on the label:
https://github.com/mvdnbrk/dhlparcel-php-api#setting-delivery-options-for-a-parcel

**Comment by olia-bn** [comment]
@mvdnbrk thanks.

So what does `reference_identifier` even do?  And is the `README.md` "reference" to `reference` correct?

**Comment by mvdnbrk** [comment]
See the docs 4.2.1: https://dhlparcel.github.io/api-gtw-docs/
Refers to `orderReference`

`reference` is a shorthand for the `reference_identifier` attribute on the Parcel resource.
