### ISSUE TITLE
Error executing API call: Could not find matching capabilities

### ISSUE THREAD

**Issue by LukaszNiziolDWG** [mvdnbrk/dhlparcel-php-api#68]
**Describe the bug**
string(86) "{"key":"capabilities_retrieve_empty","message":"Could not find matching capabilities"}"

Mvdnbrk\DhlParcel\Exceptions\DhlParcelException
Error executing API call: Could not find matching capabilities
/home/lukasz/Projekty/ecoexpress/incms/vendor/mvdnbrk/dhlparcel-php-api/src/Exceptions/DhlParcelException.php

**To Reproduce**
        $first_name = $this->input->post('first_name');
        $last_name = $this->input->post('last_name');
        $street = $this->input->post('street');
        $postal_code = $this->input->post('postal_code');
        $city = $this->input->post('city');
        $cash_on_delivery = $this->input->post('cash_on_delivery');
        $type = $this->input->post('type');
        $service_point_id = $this->input->post('service_point_id');
        
        $dhlparcel = new \Mvdnbrk\DhlParcel\Client();
        $dhlparcel->setUserId(''**********************************************');
        $dhlparcel->setApiKey('**********************************************');
        
        //Create parcel
        $parcel = new \Mvdnbrk\DhlParcel\Resources\Parcel([
//            'reference' => 'your own reference for the parcel (optional)',
            'recipient' => [
                'company_name' => 'Test sp. z o. o.',
                'first_name' => $first_name,
                'last_name' => $last_name,
                'street' => $street,
                'number' => '1',
                'number_suffix' => 'A',
                'postal_code' => $postal_code,
                'city' => $city,
                'cc' => 'PL',
                'email' => 'test@gmail.com',
                'phone' => '+486123456789',
            ],
            'sender' => [
                'company_name' => 'ALBA Nowe Technologie Sp. z o.o',
                'street' => 'Starocmentarna',
                'additional_address_line' => '',
                'number' => '2',
                'postal_code' => '41-300',
                'city' => 'Dabrowa Gornicza',
                'cc' => 'PL',
                'email' => 'test2@gmail.com',
                'phone' => '+48987654321',
            ],
            'options' => [
//                'cash_on_delivery' => $cash_on_delivery,
//                'service_point_id' => $service_point_id,
                'service_point_id' => '8004-NL-272403',
            ],
            'pieces' => [
//                'parcel_type' => $type,
                'parcel_type' => \Mvdnbrk\DhlParcel\Resources\Piece::PARCEL_TYPE_SMALL,
                'quantity' => 1,
            ],
        ]);
       
        //Create shipment
        $shipment = $dhlparcel->shipments->create($parcel);
        $shipment->id;
        // For shipments with multiple pieces:
        $shipment->pieces->each(function ($item) {
            $item->label_id;
            $item->barcode;
        });
        // For a shipment with one single piece:
        $shipment->label_id;
        $shipment->barcode;

**Expected behavior**
I want to register a new shipment

**Please complete the following information:**
 - Version of this package: v1.5.0
 - PHP Version: 7.2.34

**Comment by bastiaansenglenn** [comment]
We have encountered the same issue and contacted DHL-Parcel, they said the reason is because the company_name is set on recipient model is combination with the `isBussiness => true`.

In the recipient model file you will find the following code, here you can see the isBussiness will always be true when company_name is not empty;
![Schermafbeelding 2021-07-05 om 13 13 09](https://user-images.githubusercontent.com/33938529/124463162-c54c2e80-dd92-11eb-8291-a0304823df96.png)

The shipping method we used is a b2c method, when isBussiness is true DHL-Parcel expects a b2b shipping method.

**Comment by mvdnbrk** [comment]
Feel free to open a PR to address this issue.
